use_frameworks!

target 'BYImagePreview_Example' do
  pod 'BYImagePreview', :path => '../'

  target 'BYImagePreview_Tests' do
    inherit! :search_paths
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
    
  end
end
