source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '13.0'

target 'BYImagePreview_Example' do
  pod 'BYImagePreview', :path => '../'

  target 'BYImagePreview_Tests' do
    inherit! :search_paths
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Kingfisher', '~> 5.7'
    
  end
end
